### PR TITLE
README: update install instructions and timeout section

### PR DESCRIPTION
**Pull request by abesto**

### CODE REVIEW

**Comment by dcramer** [comment]
Actually the timeout section doesnt really apply. That was probably noted for people who had incorrectly configured Sentry (i.e. were processing jobs in the foreground which isn't production-safe)

**Comment by abesto** [comment]
Right, that makes sense. Do you think it should just be removed, or should it be there with a disclaimer along the lines of "never use Sentry without queues, but if you do, this will happen"?

**Comment by dcramer** [comment]
I think we can just remove it. The rest is good tho. If you want to update Ill merge after.

**Comment by abesto** [comment]
Is done, thanks.

**Comment by dcramer** [comment]
:+1: 

Thanks!

**Pull request merged**
