### PR TITLE
Do not create a new incident if one is already open

### PR DESCRIPTION
**Pull request by maroux**
Use the `incident_key` attribute on an event (https://developer.pagerduty.com/documentation/integration/events/trigger)

### CODE REVIEW

**Comment by dcramer** [comment]
Is your thinking that this would handle the case where a retry had to occur on creating it? Otherwise event.event_id changes with every sample from an issue.

**Comment by maroux** [comment]
Ah yes, I confused event and group.

**Comment by maroux** [comment]
This is basically so that every event in the same group doesn't end up creating a new incident in PagerDuty

**Comment by dcramer** [comment]
@maroux hopefully to avoid me looking -- if you close out a pagerduty issue, and it re-reports (with the same incident_key) will it re-open?

**Comment by maroux** [comment]
Yes, it does, from the docs:

> If there's no open (i.e. unresolved) incident with this key, a new one will be created. If there's already an > open incident with a matching key, this event will be appended to that incident's log. The event key provides an easy way to "de-dup" problem reports.

**Comment by maroux** [comment]
@dcramer unrelated, but what do you think about changing the url to event url (instead of group url)? That way you can get to the exact event that caused the pager to trip.

**Comment by dcramer** [comment]
@mattrobenolt

**Comment by dcramer** [comment]
Thanks!

**Comment by maroux** [comment]
@dcramer any idea when this will be deployed to app.getsentry.com?

**Comment by dcramer** [comment]
@maroux will go out tomorrow

**Comment by maroux** [comment]
Great, thanks!

**Pull request merged**
